---

- name: Configure txnvalidator.js
  template:
      src: txnvalidator.js.j2
      dest: /etc/sawtooth-validator/txnvalidator.js
      backup: yes

- name: Configure /etc/default/sawtooth-validator
  template:
      src: sawtooth-validator.j2
      dest: /etc/default/sawtooth-validator
      backup: yes
